Repository prgrms-be-devcourse/NBE1_2_Team09, pull requests merged in 2024-10, with the labels that each got.

#18 Feature/#9: Redis로 Token 관리 및 Cookie 활용 메서드 구현
  .gitignore
  build.gradle
  src/main/java/com/grepp/nbe1_2_team09/admin/config/RedisConfig.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/CookieUtil.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/JwtFilter.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/JwtUtil.java
  src/main/java/com/grepp/nbe1_2_team09/admin/redis/entity/RefreshToken.java
  src/main/java/com/grepp/nbe1_2_team09/admin/redis/repository/RefreshTokenRepository.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/CustomUserDetailsService.java
  src/main/java/com/grepp/nbe1_2_team09/controller/user/UserController.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/User.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/user/UserService.java
Labels: ✨ Feature

#23 Feature/#22 open ai 도입
  src/main/java/com/grepp/nbe1_2_team09/common/config/OpenAiConfig.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/AccountBookController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/dto/ChatGPTReqDTO.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/dto/ChatGPTResDTO.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/dto/Message.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/finance/OCRService.java
Labels: 🔨 Refactor

#24 Feature/#21
  build.gradle
  src/main/java/com/grepp/nbe1_2_team09/admin/config/RedisConfig.java
  src/main/java/com/grepp/nbe1_2_team09/admin/config/SecurityConfig.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/JwtUtil.java
  src/main/java/com/grepp/nbe1_2_team09/common/config/WebSocketConfig.java
  src/main/java/com/grepp/nbe1_2_team09/controller/event/EventLocationController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/group/GroupController.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/Location.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/event/EventLocation.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/group/invitation/GroupInvitation.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/group/GroupService.java
  src/main/java/com/grepp/nbe1_2_team09/notification/controller/NotificationController.java
  src/main/java/com/grepp/nbe1_2_team09/notification/controller/dto/NotificationDto.java
  src/main/java/com/grepp/nbe1_2_team09/notification/entity/Notification.java
  src/main/java/com/grepp/nbe1_2_team09/notification/repository/NotificationRepository.java
  src/main/java/com/grepp/nbe1_2_team09/notification/service/NotificationService.java
  src/test/java/com/grepp/nbe1_2_team09/domain/service/event/EventServiceTest.java
  src/test/java/com/grepp/nbe1_2_team09/domain/service/group/GroupServiceTest.java
Labels: 🐞 BugFix, ✨ Feature, ✅ Test

#26 Feature/#9: OAuth2.0 카카오 소셜로그인 구현 완료
  build.gradle
  src/main/java/com/grepp/nbe1_2_team09/admin/config/SecurityConfig.java
  src/main/java/com/grepp/nbe1_2_team09/admin/dto/CustomUserInfoDTO.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/CookieUtil.java
  src/main/java/com/grepp/nbe1_2_team09/admin/jwt/JwtUtil.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/CustomUserDetailsService.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/oauth2/KakaoApiService.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/oauth2/KakaoUserInfo.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/oauth2/OAuth2LoginFailureHandler.java
  src/main/java/com/grepp/nbe1_2_team09/admin/service/oauth2/OAuth2UserInfo.java
  src/main/java/com/grepp/nbe1_2_team09/controller/user/UserController.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/Role.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/group/GroupMembership.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/group/invitation/GroupInvitation.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/user/OAuthProvider.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/user/Role.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/user/User.java
  src/main/java/com/grepp/nbe1_2_team09/domain/repository/group/GroupInvitationRepository.java
  src/main/java/com/grepp/nbe1_2_team09/domain/repository/group/GroupMembershipRepository.java
  src/main/java/com/grepp/nbe1_2_team09/domain/repository/user/UserRepository.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/finance/AccountBookService.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/group/GroupService.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/user/UserService.java
  src/test/java/com/grepp/nbe1_2_team09/domain/service/finance/AccountBookServiceTest.java
Labels: ✨ Feature

#30 Feature/#29: 프론트쪽 사용자 정보 요청 API 추가
  src/main/java/com/grepp/nbe1_2_team09/controller/user/UserController.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/user/UserService.java
Labels: 🔨 Refactor, ✨ Feature

#33 Feature/#28
  src/main/java/com/grepp/nbe1_2_team09/Nbe12Team09Application.java
  src/main/java/com/grepp/nbe1_2_team09/controller/group/GroupController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/group/dto/GroupMembershipDto.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/group/Group.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/group/GroupService.java
  src/main/java/com/grepp/nbe1_2_team09/notification/controller/dto/NotificationDto.java
  src/main/java/com/grepp/nbe1_2_team09/notification/repository/NotificationRepository.java
  src/main/java/com/grepp/nbe1_2_team09/notification/service/NotificationService.java
Labels: 🔨 Refactor

#32 Feature: 챗봇 기능 추가
  src/main/java/com/grepp/nbe1_2_team09/controller/chatBot/ChatBotController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/chatBot/dto/ChatGPTReqDTO.java
  src/main/java/com/grepp/nbe1_2_team09/controller/chatBot/dto/ChatGPTResDTO.java
  src/main/java/com/grepp/nbe1_2_team09/controller/chatBot/dto/Message.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/AccountBookController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/finance/dto/ChatGPTReqDTO.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/chatBot/ChatBotService.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/finance/OCRService.java
Labels: ✨ Feature

#37 Feature/#7: 날씨 API 추가, 날씨 검색 및 조회기능 업데이트
  src/main/java/com/grepp/nbe1_2_team09/controller/weather/WeatherController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/weather/dto/GeocodeRes.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/weather/WeatherService.java
  voya9e_front/voya9e/src/components/WeatherSearch.js
  voya9e_front/voya9e/src/pages/MainPage.js
  voya9e_front/voya9e/src/services/api.js
Labels: ✨ Feature

#40 Fix/#38 회원 관련
  src/main/java/com/grepp/nbe1_2_team09/controller/user/UserController.java
  src/main/java/com/grepp/nbe1_2_team09/controller/user/dto/ChangePasswordReq.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/user/UserService.java
  voya9e_front/voya9e/src/pages/ChangePasswordPage.js
  voya9e_front/voya9e/src/pages/DeleteAccountPage.js
  voya9e_front/voya9e/src/pages/LoginPage.js
  voya9e_front/voya9e/src/pages/MyPage.js
  voya9e_front/voya9e/src/pages/UpdateProfilePage.js
  voya9e_front/voya9e/src/services/api.js
  voya9e_front/voya9e/src/styles/GlobalStyles.js
Labels: 🐞 BugFix

#42 Feature/41
  src/main/java/com/grepp/nbe1_2_team09/common/exception/ExceptionMessage.java
  src/main/java/com/grepp/nbe1_2_team09/controller/group/GroupController.java
  src/main/java/com/grepp/nbe1_2_team09/domain/entity/group/GroupRole.java
  src/main/java/com/grepp/nbe1_2_team09/domain/repository/group/membership/GroupMembershipRepositoryCustom.java
  src/main/java/com/grepp/nbe1_2_team09/domain/repository/user/UserRepository.java
  src/main/java/com/grepp/nbe1_2_team09/domain/service/group/GroupService.java
  src/test/java/com/grepp/nbe1_2_team09/domain/service/group/GroupServiceTest.java
  voya9e_front/voya9e/src/pages/GroupMembers.js
  voya9e_front/voya9e/src/services/api.js
Labels: 🔨 Refactor
